import { ChatPromptTemplate } from "@langchain/core/prompts";
import type { RetrievalMeta } from "./types";

export const SYSTEM_PROMPT = `You are DeployIQ, a deployment risk analysis agent. You analyze code changes in full system context — not just the diff — to produce structured risk reports.

You focus on:
- Deployment risk scoring (1-10 scale)
- Blast radius analysis (what services, files, and users are affected)
- Rollout guidance (staged deployments, feature flags, rollback plans)
- Missing safety checks (tests, monitoring, migrations, env vars)
- Incident prevention (patterns that have caused outages before)

You are NOT a code style checker. Do not comment on formatting, naming conventions, or stylistic preferences unless they directly impact deployment safety.

Your output MUST be valid JSON matching this exact schema:
{{
  "riskScore": <number 1-10>,
  "riskLevel": "<Low|Medium|High|Critical>",
  "riskFactors": ["<risk 1>", "<risk 2>", ...],
  "blastRadius": {{
    "filesAffected": <number>,
    "servicesAffected": ["<service 1>", ...]
  }},
  "deploymentRecommendations": ["<recommendation 1>", ...],
  "codeObservations": ["<observation 1>", ...]
}}

Risk score guide:
- 1-3 (Low): Cosmetic changes, docs, tests only
- 4-6 (Medium): Logic changes with good test coverage, no infra changes
- 7-8 (High): Database changes, new dependencies, API contract changes
- 9-10 (Critical): Infrastructure changes, auth/security changes, data migrations`;

export const REVIEW_PROMPT = ChatPromptTemplate.fromMessages([
    ["system", SYSTEM_PROMPT],
    [
        "human",
        `Analyze this pull request for deployment risk.

## PR Info
- **Title**: {prTitle}
- **Description**: {prBody}
- **Base branch**: {baseBranch} ← **Head branch**: {headBranch}
- **Changed files**: {changedFiles}

## Diff
\`\`\`
{diff}
\`\`\`

## Relevant Code Context (from repository)
{codeContext}

## Past Review Context (similar changes)
{reviewContext}

Analyze the deployment risk and respond with the JSON schema specified in your instructions.`,
    ],
]);

export function formatCodeContext(
    relevantCode: Array<{ content: string; filePath: string }>
): string {
    if (relevantCode.length === 0) {
        return "No additional code context available.";
    }

    return relevantCode
        .map(
            (chunk) =>
                `### ${chunk.filePath}\n\`\`\`\n${chunk.content}\n\`\`\``
        )
        .join("\n\n");
}

export function formatReviewContext(
    pastReviews: Array<{ content: string; prTitle: string }>
): string {
    if (pastReviews.length === 0) {
        return "No past review context available.";
    }

    return pastReviews
        .map((review) => `### PR: ${review.prTitle}\n${review.content}`)
        .join("\n\n");
}

export function formatReviewMarkdown(review: {
    riskScore: number;
    riskLevel: string;
    riskFactors: string[];
    blastRadius: { filesAffected: number; servicesAffected: string[] };
    deploymentRecommendations: string[];
    codeObservations: string[];
    retrieval?: RetrievalMeta;
}): string {
    const riskEmoji =
        review.riskLevel === "Critical"
            ? "🔴"
            : review.riskLevel === "High"
              ? "🟠"
              : review.riskLevel === "Medium"
                ? "🟡"
                : "🟢";

    const retrievalWarning =
        review.retrieval?.status === "degraded"
            ? `> Context retrieval degraded for this run. DeployIQ generated the report with partial or unavailable repository context.\n\n`
            : "";

    return `## DeployIQ Risk Assessment

${riskEmoji} **Risk Score: ${review.riskScore}/10** (${review.riskLevel})

${retrievalWarning}### Risk Factors
${review.riskFactors.map((f) => `- ${f}`).join("\n")}

### Blast Radius
Files affected: ${review.blastRadius.filesAffected} | Services affected: ${review.blastRadius.servicesAffected.join(", ") || "None identified"}

### Deployment Recommendations
${review.deploymentRecommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

### Code Observations
${review.codeObservations.map((o) => `- ${o}`).join("\n")}

---
*Generated by [DeployIQ](https://deployiq.dev) — deployment risk analysis, not code review.*`;
}
